#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-serial
#SBATCH -o auto-serial.out
#SBATCH -t 00:10:00
#SBATCH -N 1

#N = {100000 1000000 10000000}
#M = {1 10 100 1000}
#K = {2 5 10}

for nn in 10000 100000 1000000 10000000:
do
    echo $nn
    for mm in 5 10 100 1000 10000:
        do
            for kk in 1 10 100 1000:
            do
							./serial -o serial.out -n $nn -m $mm -k $kk
	    			done
				done
done
