#!/bin/bash
#SBATCH -A mp309
#SBATCH -C knl,quad,cache
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 1          # you'll never need more than 1 node for the openmp code
#SBATCH -t 00:30:00   # adjust the amount of time as necessary
#SBATCH -J KMEANSKNLserial
#SBATCH -o openmp_res.txt
#SBATCH -e openmp_res.txt

for nn in 1000 10000 100000 1000000:
do
  echo $nn
  for mm in 1 10 1000 5000:
      do
          for kk in 2 5 10:
          do
						./serial_knl -o serial_knl.out -n $nn -m $mm -k $kk
    			done
			done
done
