#!/bin/bash
#SBATCH -A mp309
#SBATCH -C haswell
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 1          # you'll never need more than 1 node for the openmp code
#SBATCH -t 00:20:00   # adjust the amount of time as necessary
#SBATCH -J KMEANSOPENMP
#SBATCH -o openmp_res.txt
#SBATCH -e openmp_res.txt


export OMP_NUM_THREADS=32

for nn in 10000 100000 1000000 10000000:
do
    echo $nn
    for mm in 5 10 100 1000 10000:
        do
            for kk in 1 10 100 1000:
            do
							for pp in 2 4 6 12 18 24 32
							do
								srun -N 1 -n 1 -c 32 ./omp -o omp.out -n $nn -m $mm -k $kk -p $pp
							done
            done
        done
done
