#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug            # change this option for non-debug runs
#SBATCH -N 1                # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00         # adjust the amount of time as necessary
#SBATCH -J auto-upc
#SBATCH -o auto-upc.stdout
#SBATCH -e auto-upc.error

echo test

srun -N 1 -n 1 upc 
