#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug            # change this option for non-debug runs
#SBATCH -N 1                # you'll never need more than 1 node for the serial code
#SBATCH -t 00:30:00         # adjust the amount of time as necessary
#SBATCH -J auto-upc
#SBATCH -o upc_large.stdout
#SBATCH -e upc_large.error

export GASNET_MAX_SEGSIZE=1024GB 
export UPCXX_SEGMENT_MB=4096GB

for nn in 1000000:
do
    for mm in 1000 5000:
  	do
     	    for kk in 2 5 10:
		do
		    for n in 1 2 4 6 8 16 32 64
			do
			srun -N 1 -n $n ./upc -o upc_haswell_large.out -n $nn -m $mm -k $kk
			done
		done
  	done
  done
