#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug            # change this option for non-debug runs
#SBATCH -N 2                # you'll never need more than 1 node for the serial code
#SBATCH -t 00:30:00         # adjust the amount of time as necessary
#SBATCH -J auto-upc
#SBATCH -o upc_hsw.stdout
#SBATCH -e upc_hsw.error

export GASNET_MAX_SEGSIZE=1024GB 
export UPCXX_SEGMENT_MB=4096GB

for nn in 10000:
do
    for mm in 5000:
  	do
     	for kk in 10:
		do
		    for n in 8 16 32 64
				do
				srun -N 2 -n $n ./upc_old -o upc_old_5000.out -n $nn -m $mm -k $kk
			done
		done
  	done
done
