#!/bin/bash
#SBATCH -A mp309
#SBATCH -C knl,quad,cache
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 1          # you'll never need more than 1 node for the openmp code
#SBATCH -t 00:30:00   # adjust the amount of time as necessary
#SBATCH -J KMEANSOMPKNL
#SBATCH -o auto_upc_knl.stdout
#SBATCH -e auto_upc_knl.error

for nn in 1000 10000 100000 1000000:
do
    for mm in 1000 5000:
        do
            for kk in 2 5 10:
                do
                    for n in 1 2 4 6 8 16 32 64
                        do
                        srun -N 1 -n $n ./upc -o upc.out -n $nn -m $mm -k $kk
                        done
                done
        done
  done